#!/bin/sh

brew cask install 1password
brew cask install charles
brew cask install flux
brew cask install google-chrome
brew cask install gpgtools
brew cask install postman
brew cask install skype
brew cask install slack
brew cask install sourcetree
brew cask install spotify
brew cask install whatsapp
brew cask install atom
